# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'Invoiced'),
                    ('pending', 'Payment pending'),
                    ('paid', 'Payment received'),
                    ('canceled', 'Invoice canceled'),
                ], default='new', max_length=128),
        ),
    ]
