# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiced_entity',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
