# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField(blank=True)),
                ('childcare', models.BooleanField()),
                ('childcare_needs', models.TextField(blank=True)),
                ('childcare_details', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('family_usernames', models.TextField(blank=True)),
                ('room', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AccommNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametag_2', models.CharField(blank=True, max_length=50)),
                ('nametag_3', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.TextField(blank=True)),
                ('announce_me', models.BooleanField()),
                ('register_announce', models.BooleanField()),
                ('register_discuss', models.BooleanField()),
                ('coc_ack', models.BooleanField(default=False)),
                ('fee', models.CharField(blank=True, max_length=5)),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('final_dates', models.BooleanField(default=False)),
                ('reconfirm', models.BooleanField(default=False)),
                ('t_shirt_cut', models.CharField(blank=True, max_length=1)),
                ('t_shirt_size', models.CharField(blank=True, max_length=8)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('languages', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_register_steps', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(blank=True, max_length=16)),
                ('gluten_free', models.BooleanField()),
                ('special_diet', models.TextField(blank=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='register.Attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('meal', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set([('date', 'meal')]),
        ),
        migrations.AddField(
            model_name='food',
            name='meals',
            field=models.ManyToManyField(to='register.Meal'),
        ),
        migrations.AddField(
            model_name='accomm',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accomm', to='register.Attendee'),
        ),
        migrations.AddField(
            model_name='accomm',
            name='nights',
            field=models.ManyToManyField(to='register.AccommNight'),
        ),
    ]
