# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_attendee_invoice_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='invoiced_entity',
            field=models.TextField(blank=True),
        ),
    ]
