# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_attendee_invoiced_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommnight',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='pgp_fingerprints',
            field=models.TextField(blank=True),
        ),
    ]
