# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_shirt', models.BooleanField(default=False)),
                ('swag', models.BooleanField(default=False)),
                ('nametag', models.BooleanField(default=False)),
                ('debcamp_meal_card', models.BooleanField(default=False)),
                ('debconf_meal_card', models.BooleanField(default=False)),
                ('room_key', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('attendee', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_in', to='register.Attendee')),
            ],
        ),
    ]
