# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_desk', '0002_key_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
